During Travis build, make sure PHP parser is up to date

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -54,8 +54,16 @@ script:
       # failed `stat` calls from `filemtime()`.
       npm install || exit 1
       npm run build || exit 1
-      # Syntax check for php-pegjs parser
+      # Make sure phpegjs parser is up to date
       node bin/create-php-parser.js || exit 1
+      if ! git diff --quiet --exit-code lib/parser.php; then
+        echo 'ERROR: The PEG parser has been updated, but the generated PHP version'
+        echo '       (lib/parser.php) has not.  Run `bin/create-php-parser.js` and'
+        echo '       commit the resulting changes to resolve this.'
+        sleep .2 # Otherwise Travis doesn't want to print the whole message
+        exit 1
+      fi
+      # Check parser syntax
       php lib/parser.php || exit 1
       # Run PHPUnit tests
       RUN_PARSER_TESTS=1 phpunit || exit 1
